### ISSUE TITLE
ExecJS::RuntimeError: unexpected identifier

### ISSUE THREAD

**Issue by manjunath-nm89** [emilioforrer/haml_coffee_assets#137]
I'm running an app on Rails 3.2.11. I get Execjs Runtime Error on assets_precompile during production deployment. Though on-the-fly compilation works fine for me in my local development environment.

Also, assets_precompile used to happen fine on Rails 3.1, this issue has cropped up only after upgrade to Rails 3.2

Here is my stacktrace of the exception during assets_precompile in production.

```
ExecJS::RuntimeError: [stdin]:51:80: error: unexpected identifier
** text = text.replace(/\r/g, '').replace ///<(#{ tags })>([\s\S]*?)<\/\1>/// g, (str, tag, content) ->
(in /gems/haml_coffee_assets-1.16.0/vendor/assets/javascripts/hamlcoffee_amd.js.coffee.erb)
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:47:in `rescue in block in call'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:44:in `block in call'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:73:in `call'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
** /gems/execjs-2.5.2/lib/execjs/ruby_racer_runtime.rb:43:in `call'
** /gems/coffee-script-2.2.0/lib/coffee_script.rb:57:in `compile'
** /gems/tilt-1.4.1/lib/tilt/coffee.rb:46:in `evaluate'
```

Here are my versions

execjs - 2.5.2
thrubyracer - 0.12.2
Rails - 3.2.11
Ruby - 1.9.1
sass-rails - 3.2.6
sprockets - 2.2.3
coffee-rails - 3.2.2
haml_coffee_assets - 1.16.0

I tried upgrading execjs, but faced the same kind of issues.

**Comment by manjunath-nm89** [comment]
I have a sent out a pull request for this.

https://github.com/netzpirat/haml_coffee_assets/pull/138
