### ISSUE TITLE
CVE fixing Rails 3.2.22.2 breaks compability with haml_coffee_assets:   wrong number of arguments (5 for 4)

### ISSUE THREAD

**Issue by lichtamberg** [emilioforrer/haml_coffee_assets#150]
Upgraded to 3.2.22.2, then i got serval errors. All of them disappeared when reverting back to 3.2.22.1..

Here is the backtrace:

```
 wrong number of arguments (5 for 4)
 haml_coffee_assets (1.16.0) lib/haml_coffee_assets/action_view/resolver.rb:10:in `find_templates'

haml_coffee_assets (1.16.0) lib/haml_coffee_assets/action_view/resolver.rb:10:in `find_templates'
 actionpack (3.2.22.2) lib/action_view/template/resolver.rb:46:in `block in find_all'
 actionpack (3.2.22.2) lib/action_view/template/resolver.rb:81:in `cached'
 actionpack (3.2.22.2) lib/action_view/template/resolver.rb:45:in `find_all'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:82:in `block (2 levels) in _find_all'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:78:in `each'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:78:in `block in _find_all'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:77:in `each'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:77:in `_find_all'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:66:in `find_all'
 actionpack (3.2.22.2) lib/action_view/path_set.rb:58:in `find'
 actionpack (3.2.22.2) lib/action_view/lookup_context.rb:122:in `find'
 actionpack (3.2.22.2) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
 actionpack (3.2.22.2) lib/action_view/renderer/template_renderer.rb:35:in `determine_template'
 newrelic_rpm (3.12.1.298) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:147:in `render_with_newrelic'
 actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:41:in `render_template'
 actionpack (3.2.22.2) lib/action_view/renderer/renderer.rb:22:in `render'
 actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:110:in `_render_template'
 actionpack (3.2.22.2) lib/action_controller/metal/streaming.rb:225:in `_render_template'
 actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:103:in `render_to_body'
 actionpack (3.2.22.2) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
 actionpack (3.2.22.2) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
 actionpack (3.2.22.2) lib/abstract_controller/rendering.rb:88:in `render'
 actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:16:in `render'
 actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
 activesupport (3.2.22.2) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
 /home/deployer/.rbenv/versions/2.1.5/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
 activesupport (3.2.22.2) lib/active_support/core_ext/benchmark.rb:5:in `ms'
 actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
 actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
 activerecord (3.2.22.2) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
 actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:39:in `render'
 actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
 actionpack (3.2.22.2) lib/action_controller/metal/responder.rb:232:in `default_render'
 actionpack (3.2.22.2) lib/action_controller/metal/responder.rb:160:in `to_html'
 actionpack (3.2.22.2) lib/action_controller/metal/responder.rb:153:in `respond'
 actionpack (3.2.22.2) lib/action_controller/metal/responder.rb:146:in `call'
 actionpack (3.2.22.2) lib/action_controller/metal/mime_responds.rb:239:in `respond_with'
 devise (3.5.1) app/controllers/devise/sessions_controller.rb:21:in `create'
 actionpack (3.2.22.2) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 actionpack (3.2.22.2) lib/abstract_controller/base.rb:167:in `process_action'
 actionpack (3.2.22.2) lib/action_controller/metal/rendering.rb:10:in `process_action'
 actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
 activesupport (3.2.22.2) lib/active_support/callbacks.rb:469:in `_run__4019639717491155057__process_action__1102486407995859360__callbacks'
 activesupport (3.2.22.2) lib/active_support/callbacks.rb:405:in `__run_callback'
 activesupport (3.2.22.2) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
 activesupport (3.2.22.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
 actionpack (3.2.22.2) lib/abstract_controller/callbacks.rb:17:in `process_action'
 actionpack (3.2.22.2) lib/action_controller/metal/rescue.rb:29:in `process_action'
 actionpack (3.2.22.2) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
 activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `block in instrument'
 activesupport (3.2.22.2) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 activesupport (3.2.22.2) lib/active_support/notifications.rb:123:in `instrument'
```

**Comment by TheKidCoder** [comment]
Fixed in 1.16.2. Closing.
